# Generated by Django 4.0.4 on 2022-06-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('transparency', models.BooleanField()),
                ('control', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='the related question')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedOn', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.participant', verbose_name='the related participant')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scenario', verbose_name='the related scenario')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='scenarios',
            field=models.ManyToManyField(through='api.Completion', to='api.scenario'),
        ),
    ]
