# Generated by Django 4.0.4 on 2022-06-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_scenario_system_remove_completion_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.CharField(choices=[('WELL', 'User wellbeing'), ('EVAL', 'System evaluation')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.option', verbose_name='the chosen option')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.participant', verbose_name='the active participant')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.system', verbose_name='the evaluated system')),
            ],
        ),
    ]
