# Generated by Django 4.0.4 on 2022-06-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_option_question_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.ImageField(default='emoji-5.svg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='variant',
            field=models.CharField(choices=[('WELL', 'Wellbeing'), ('EVAL', 'Evaluation')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant',
            field=models.CharField(choices=[('WELL', 'Wellbeing'), ('EVAL', 'Evaluation')], max_length=4, null=True),
        ),
    ]
