# Generated by Django 4.0.4 on 2022-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_answer_question_option_image_option_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smiley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='image',
        ),
    ]
