# Generated by Django 4.0.4 on 2022-06-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_answer_option_answer_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='systems',
            new_name='completions',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.option', verbose_name='chosen option'),
            preserve_default=False,
        ),
    ]
