# Generated by Django 4.0.4 on 2022-06-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='options',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.scale', verbose_name='scale'),
        ),
    ]
