# Generated by Django 4.0.4 on 2022-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_scale_options_remove_scale_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
