# Generated by Django 4.0.4 on 2022-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_option_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
