# Generated by Django 4.0.4 on 2022-06-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_option_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.scale', verbose_name='scale'),
        ),
    ]
