# Generated by Django 4.0.4 on 2022-06-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_option_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options', to='api.scale', verbose_name='scale'),
        ),
    ]
