# Generated by Django 4.0.4 on 2022-06-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_option_scale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smiley',
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('value',)},
        ),
        migrations.AddField(
            model_name='system',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
