# Generated by Django 4.0.4 on 2022-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_delete_smiley_alter_option_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.CharField(max_length=160, primary_key=True, serialize=False),
        ),
    ]
