# Generated by Django 4.0.4 on 2022-07-29 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_participant_email_remove_participant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='creationTime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
