# Generated by Django 4.0.4 on 2022-08-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_interaction_remove_participant_completions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='participant_id',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='system_id',
            new_name='system',
        ),
    ]
