# Generated by Django 4.0.4 on 2022-08-02 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_interaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='ranking',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
