# Generated by Django 4.0.4 on 2022-08-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_interaction_ranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('variant', 'scale')},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='ranking',
            new_name='user_ranking',
        ),
        migrations.AlterField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant', verbose_name='participant'),
        ),
    ]
