# Generated by Django 4.0.4 on 2022-08-02 12:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_question_options_alter_system_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='system_ranking',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
