# Generated by Django 4.0.4 on 2022-08-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_interaction_system_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.CharField(choices=[('00_18', 'Under 18'), ('18_24', ' 18 24'), ('25_34', ' 25 34'), ('35_44', ' 35 44'), ('45_54', ' 45 54'), ('55_00', ' 55'), ('DEF', 'Default')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='education',
            field=models.CharField(choices=[('UND', 'Under'), ('SEC', 'Secondary'), ('FHS', 'Fachhochschule'), ('APP', 'Apprenticeship'), ('TRA', 'Trade Technical'), ('BAC', 'Bachelor'), ('MAS', 'Master'), ('PHD', 'Phd'), ('DEF', 'Default')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('MAL', 'Male'), ('FEM', 'Female'), ('OTH', 'Other'), ('DEF', 'Default')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.system', verbose_name='related system'),
        ),
    ]
