# Generated by Django 4.0.4 on 2022-06-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_scenario_option_completion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scenario',
            new_name='System',
        ),
        migrations.RemoveField(
            model_name='completion',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='scenarios',
        ),
        migrations.AddField(
            model_name='completion',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.system', verbose_name='the related system'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='systems',
            field=models.ManyToManyField(blank=True, through='api.Completion', to='api.system'),
        ),
    ]
