# Generated by Django 4.0.4 on 2022-06-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_answer_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.question', verbose_name='question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.participant', verbose_name='participant'),
        ),
    ]
