# Generated by Django 4.0.4 on 2022-06-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_answer_question_alter_answer_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
