# Generated by Django 4.0.4 on 2022-06-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_option_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.option', verbose_name='option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.question', verbose_name='question')),
            ],
        ),
    ]
