# Generated by Django 4.0.4 on 2022-08-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_interaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together=set(),
        ),
    ]
