# Generated by Django 4.0.4 on 2022-08-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_interaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('participant', 'system')},
        ),
    ]
